name: build-test-publish
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: ./fore

      - name: Run tests
        run: npm test
        working-directory: ./fore

      - name: Build package (if necessary)
        run: npm run build
        working-directory: ./fore

      - name: Publish to npm
        run: npm publish
        working-directory: ./fore
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
